### ISSUE TITLE
'Run shell script on wake or suspend' multiple commands

### ISSUE THREAD

**Issue by SteUK** [freshollie/AndroidHeadunitController#6]
What format would this take for multiple commands?  Line broken?  All one one line with '&&' between?

On suspend I am trying to:
- disable wifi
- disable bluetooth
- engage airplane mode

...then reverse that on wake.

Currently using the built in Timur scripts you put in /data/local/ but it seems hit and miss.

**Comment by freshollie** [comment]
The command is executed as a single line. `su -c <command>`. However you want to represent a single line command it's up to you. Multiple lines will work as long as it's valid syntax. Unfortunately I do not provide error output (Might be a good idea).

Please see https://github.com/freshollie/headunit-controller-android/blob/4dc9b0ba4de1165d346fa85365214ba5cd6f8773/app/src/main/java/com/freshollie/headunitcontroller/services/controllers/MainController.java#L125 and https://github.com/freshollie/headunit-controller-android/blob/4dc9b0ba4de1165d346fa85365214ba5cd6f8773/app/src/main/java/com/freshollie/headunitcontroller/util/SuperuserManager.java#L41

**Comment by SteUK** [comment]
Awesome, cool, thanks for the info!
